import Alert, { IAlert } from "../../models/alert.model.js";
import Detection from "../../models/detection.model.js";
import Farm from "../../models/farm.model.js";
import AppError from "../../utils/AppError.js";
import { notifyDiseaseAlert } from "../../services/notification.service.js";
import { emitToAll } from "../../socket/socket.js";
import { SOCKET_EVENTS } from "../../socket/socket.events.js";
import { CreateAlertInput, AlertQueryInput } from "./alert.validation.js";

// ─────────────────────────────────────────────
// Helper: Notify farmers in region
// ─────────────────────────────────────────────

const notifyFarmersInRegion = async (
  alert: IAlert,
  region: string,
  cropType: string
): Promise<void> => {
  const farms = await Farm.find({ region })
    .select("owner")
    .lean();

  if (!farms.length) return;

  const ownerIds = [...new Set(farms.map((f) => f.owner.toString()))];

  const alreadyNotified = new Set(
    (alert.notifiedUsers || []).map((id) => id.toString())
  );

  const toNotify = ownerIds.filter((id) => !alreadyNotified.has(id));

  if (!toNotify.length) return;

  await Promise.all(
    toNotify.map((userId) =>
      notifyDiseaseAlert(
        userId,
        alert._id.toString(),
        alert.diseaseName,
        region,
        cropType
      )
    )
  );

  await Alert.findByIdAndUpdate(alert._id, {
    $addToSet: { notifiedUsers: { $each: toNotify } },
  });

  emitToAll(SOCKET_EVENTS.ALERT_NEW, {
    alertId: alert._id,
    diseaseName: alert.diseaseName,
    cropType,
    region,
    outbreakLevel: alert.outbreakLevel,
  });

  console.log(
    `🚨 Notified ${toNotify.length} farmers for ${alert.diseaseName} in ${region}`
  );
};

// ─────────────────────────────────────────────
// Create manual alert (admin)
// ─────────────────────────────────────────────

const createAlert = async (
  adminId: string,
  data: CreateAlertInput
): Promise<IAlert> => {
  const existing = await Alert.findOne({
    diseaseName: data.diseaseName,
    region: data.region,
    cropType: data.cropType,
    isActive: true,
  });

  if (existing) {
    throw new AppError(
      "An active alert already exists for this disease in this region",
      409
    );
  }

  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 30);

  const alert = await Alert.create({
    ...data,
    isAutoGenerated: false,
    createdBy: adminId,
    expiresAt,
  });

  notifyFarmersInRegion(alert, data.region, data.cropType).catch((err) =>
    console.error("Notification failed:", err)
  );

  return alert;
};

// ─────────────────────────────────────────────
// Get alerts (filtered + paginated)
// ─────────────────────────────────────────────

const getAlerts = async (query: AlertQueryInput) => {
  const { region, cropType, outbreakLevel, page, limit } = query;
  const skip = (page - 1) * limit;

  const filter: any = {
    isActive: true,
    expiresAt: { $gt: new Date() },
  };

  if (region) filter.region = region;
  if (cropType) filter.cropType = cropType;
  if (outbreakLevel) filter.outbreakLevel = outbreakLevel;

  const [alerts, total] = await Promise.all([
    Alert.find(filter)
      .sort({ outbreakLevel: -1, createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .populate("createdBy", "name"),
    Alert.countDocuments(filter),
  ]);

  return {
    alerts,
    meta: {
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    },
  };
};

// ─────────────────────────────────────────────
// Farmer-specific alerts
// ─────────────────────────────────────────────

const getAlertsForFarmer = async (farmerId: string): Promise<IAlert[]> => {
  const farms = await Farm.find({ owner: farmerId, isActive: true })
    .select("region cropType")
    .lean();

  if (!farms.length) return [];

  const regions = [...new Set(farms.map((f) => f.region))];
  const cropTypes = [...new Set(farms.map((f) => f.cropType))];

  return Alert.find({
    isActive: true,
    expiresAt: { $gt: new Date() },
    $or: [
      { region: { $in: regions } },
      { cropType: { $in: cropTypes } },
    ],
  }).sort({ outbreakLevel: -1, createdAt: -1 });
};

// ─────────────────────────────────────────────
// Single alert
// ─────────────────────────────────────────────

const getAlertById = async (alertId: string): Promise<IAlert> => {
  const alert = await Alert.findById(alertId).populate("createdBy", "name");

  if (!alert) {
    throw new AppError("Alert not found", 404);
  }

  return alert;
};

// ─────────────────────────────────────────────
// Deactivate alert
// ─────────────────────────────────────────────

const deactivateAlert = async (alertId: string): Promise<IAlert> => {
  const alert = await Alert.findByIdAndUpdate(
    alertId,
    { isActive: false },
    { new: true }
  );

  if (!alert) {
    throw new AppError("Alert not found", 404);
  }

  return alert;
};

// ─────────────────────────────────────────────
// Delete alert
// ─────────────────────────────────────────────

const deleteAlert = async (alertId: string): Promise<void> => {
  const alert = await Alert.findByIdAndDelete(alertId);

  if (!alert) {
    throw new AppError("Alert not found", 404);
  }
};

// ─────────────────────────────────────────────
// Cron: outbreak detection
// ─────────────────────────────────────────────

export const detectOutbreaks = async (): Promise<void> => {
  console.log("🔍 Running outbreak detection...");

  const windowStart = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const outbreakCandidates = await Detection.aggregate([
    {
      $match: {
        status: "COMPLETED",
        createdAt: { $gte: windowStart },
        "aiResult.isHealthy": false,
        "aiResult.diseaseName": { $exists: true, $ne: null },
      },
    },
    {
      $lookup: {
        from: "farms",
        localField: "farm",
        foreignField: "_id",
        as: "farmData",
      },
    },
    {
      $match: {
        "farmData.0": { $exists: true },
      },
    },
    {
      $group: {
        _id: {
          diseaseName: "$aiResult.diseaseName",
          region: { $first: "$farmData.region" },
          cropType: "$cropType",
        },
        detectionCount: { $sum: 1 },
        affectedOwners: { $addToSet: "$owner" },
      },
    },
    {
      $match: {
        detectionCount: { $gte: 5 },
      },
    },
  ]);

  if (!outbreakCandidates.length) {
    console.log("✅ No outbreaks detected");
    return;
  }

  for (const candidate of outbreakCandidates) {
    const { diseaseName, region, cropType } = candidate._id;
    const { detectionCount, affectedOwners } = candidate;

    const existing = await Alert.findOne({
      diseaseName,
      region,
      isActive: true,
    });

    if (existing) continue;

    let outbreakLevel: "WATCH" | "WARNING" | "CRITICAL" = "WATCH";

    if (detectionCount >= 20) outbreakLevel = "CRITICAL";
    else if (detectionCount >= 10) outbreakLevel = "WARNING";

    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 14);

    const alert = await Alert.create({
      diseaseName,
      cropType,
      region,
      outbreakLevel,
      description: `Automated alert: ${detectionCount} cases of ${diseaseName} detected in ${region}.`,
      detectionCount,
      affectedFarmCount: affectedOwners.length,
      isAutoGenerated: true,
      expiresAt,
    });

    console.log(
      `🚨 Auto-alert created: ${diseaseName} in ${region} (${outbreakLevel})`
    );

    await notifyFarmersInRegion(alert, region, cropType);
  }
};

// ─────────────────────────────────────────────
// Export service
// ─────────────────────────────────────────────

const alertService = {
  createAlert,
  getAlerts,
  getAlertsForFarmer,
  getAlertById,
  deactivateAlert,
  deleteAlert,
  detectOutbreaks,
};

export default alertService;