import mongoose, { Schema } from "mongoose";

export type OutbreakLevel = "WATCH" | "WARNING" | "CRITICAL";

export interface IAlert extends Document {
  diseaseName: string;
  cropType: string;
  region: string;
  outbreakLevel: OutbreakLevel;
  description: string;
  affectedFarmCount: number;
  detectionCount: number;
  isActive: boolean;
  isAutoGenerated: boolean;
  createdBy?: mongoose.Types.ObjectId;
  notifiedUsers: mongoose.Types.ObjectId[];
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const alertSchema = new Schema<IAlert>(
  {
    diseaseName: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },

    cropType: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },

    region: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },

    outbreakLevel: {
      type: String,
      enum: ["WATCH", "WARNING", "CRITICAL"],
      required: true,
    },

    description: {
      type: String,
      required: true,
      trim: true,
      maxlength: 1000,
    },

    affectedFarmCount: {
      type: Number,
      default: 0,
    },

    detectionCount: {
      type: Number,
      default: 0,
    },

    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },

    isAutoGenerated: {
      type: Boolean,
      default: false,
    },

    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    notifiedUsers: {
      type: [Schema.Types.ObjectId],
      ref: "User",
      default: [],
      select: false,
    },

    expiresAt: {
      type: Date,
      required: true,
      index: true,
    },
  },
  { timestamps: true }
);

/**
 * Prevent duplicate active alerts for same disease-region-crop
 */
alertSchema.index(
  { isActive: 1, region: 1, diseaseName: 1, cropType: 1 },
  { unique: false }
);

/**
 * Future-ready index for cron outbreak detection queries
 */
alertSchema.index({ region: 1, diseaseName: 1, createdAt: -1 });

const Alert = mongoose.model<IAlert>("Alert", alertSchema);
export default Alert;